Repository rustodon/rustodon, pull requests merged in 2018-06, with the labels that each got.

#65 database: reorganize models into their own separate files
  database/src/idgen.rs
  database/src/lib.rs
  database/src/models.rs
  database/src/models/account.rs
  database/src/models/follow.rs
  database/src/models/mod.rs
  database/src/models/status.rs
  database/src/models/user.rs
  src/routes/ui/auth.rs
  src/routes/ui/mod.rs
Labels: A-database, enhancement :sparkles:

#68 Implement nodeinfo
  database/src/models/status.rs
  database/src/models/user.rs
  src/main.rs
  src/routes/ap.rs
  src/routes/mod.rs
  src/routes/well_known.rs
Labels: A-federation, enhancement :sparkles:

#70 Askama Templates
  Cargo.lock
  Cargo.toml
  Procfile
  build.rs
  database/src/idgen.rs
  database/src/lib.rs
  database/src/models/account.rs
  database/src/models/status.rs
  src/main.rs
  src/routes/ui/auth.rs
  src/routes/ui/mod.rs
  src/routes/ui/templates.rs
  src/routes/ui/view_helpers.rs
  src/routes/well_known.rs
  src/templates/mod.rs
  src/transform.rs
  templates/base.html
  templates/edit_profile.html
  templates/index.html
  templates/signin.html
  templates/signup.html
  templates/status.html
  templates/user.html
Labels: :thinking: WIP, A-frontend
